### PR TITLE
Remove business sectors from email-alert-api

### PR DESCRIPTION
**Pull request by leenagupte**
Trello: https://trello.com/c/ZufSHOpe

Following https://trello.com/c/0rDl6oiK/232-simplify-email-alerts-for-business-finder and https://trello.com/c/pH0tEctw/242-migrate-all-existing-business-finder-email-subscriptions, email alerts are no longer driven from the different facets for the business finder, they only require `appear_in_find_eu_exit_guidance_business_finder`.

This means we can remove https://github.com/alphagov/email-alert-api/blob/daf1251e777733dc2a8dee45e4f3b62d17d34043/spec/lib/business_readiness/examples/facet_config.yml and the associated logic.

### CODE REVIEW

**Comment by vanitabarrett** [comment]
LGTM! Do we want to remove the rake task that moves old business subscriptions to the new one?

**Comment by leenagupte** [comment]
@vanitabarrett I've removed the migration task too.

**Comment by vanitabarrett** [comment]
@leenagupte I think you need to remove the rake task associated with it too, not just the method it calls

**Comment by bevanloon** [comment]
Does this mean you can get rid of https://github.com/alphagov/govuk-app-deployment/blob/fb3f9b40ecaf92f54a92dce290f245606060011f/email-alert-api/config/deploy.rb#L5 as well?

**Comment by leenagupte** [comment]
> @leenagupte I think you need to remove the rake task associated with it too, not just the method it calls

Done! 🤦‍♀️

**Comment by leenagupte** [comment]
> Does this mean you can get rid of https://github.com/alphagov/govuk-app-deployment/blob/fb3f9b40ecaf92f54a92dce290f245606060011f/email-alert-api/config/deploy.rb#L5 as well?

No, we still need the CSV file to know which content items to add the `appear_in_find_eu_exit_guidance_business_finder` tag to.

**Pull request merged**
