### PR TITLE
Get data hygiene SQL from helm-charts

### PR DESCRIPTION
**Pull request by KludgeKML**
- removes local copy, ensures tests are always run against the hygiene code that's actually being used in the actual db backup.

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

### CODE REVIEW

**Review by sengi — APPROVED** [review]
Thanks for addressing this — clears an item from my todo list!

This adds a network dependency (and a third-party one at that) to your testsuite — if you're really ok with that then not gonna stand in your way, but you might wanna consider fetching the file ahead of time (outside the testsuite itself).

**Comment by KludgeKML** [comment]
Yeah, it's not 100% ideal, but I think reasonably the dependency here is on a github site, so since it'll be running from dev machines or github actions, we'll probably have larger problems if it fails. I might just double check that it's not making multiple calls, though (I think a let shouldn't, but I might be making a bad assumption)

**Comment by sengi** [comment]
No probs 👍  it's arguably less bad than not having the test automated 🤷😅

**Comment by KludgeKML** [comment]
It was making multiple calls. Sorted that out, which makes it a bit easier to add a non-network fallback later on if this ends up causing problems.

**Pull request merged**
