### PR TITLE
Rescue ActiveRecord::NotFound

### PR DESCRIPTION
**Pull request by gpeng**
Rescue by default and return `status: 404`

### CODE REVIEW

**Comment by kevindew** [comment]
@gpeng Looks good, but I'm just wondering if we don't get this behaviour from rails by default?

**Comment by bevanloon** [comment]
also - this is in https://github.com/alphagov/email-alert-api/pull/251/commits/de791064e406e87a82def62941dae66378ef207d but with a `render plain` is it important to get it in sooner and do we care about `plain` vs `json`?

**Comment by gpeng** [comment]
@bevanloon We've taken it out from there. @kevindew We were trying to get it to return the 404 in request specs too instead of raising but it turns out there's config that does that so I'll close this.

**Comment by kevindew** [comment]
@gpeng Oh very cool about the config option. I've always done the nasty expect raise and that always felt wrong in request specs.

**Pull request closed without merging**
