### PR TITLE
Add content IDs to Subscriber Lists

### PR DESCRIPTION
**Pull request by mobaig**
NOTE: review this by clicking on each commit, the entire diff is a bit noisy.

As part of the move towards identifying taggable content via unique content_ids,
and consequently handling email subscriptions and alerts via the same,
this commit does the following:

- Adds content_id to the SubscriberList model.
- Adds a factory method to build SubscriberLists, moving this logic out
  of the controller.

Trello: https://trello.com/c/ZD65QUBN/326-email-alerts-based-on-links-hash

### CODE REVIEW

**Comment by bradwright** [comment]
Not sure about this - does it make moving the Whitehall matrix-like topics to this API impossible? They're more like stored queries, not pieces of content. cc @elliotcm

**Comment by rboulton** [comment]
Ah, this isn't quite how I'd envisioned it: I'd expected to maintain the tags structure, but reference the tags by content_id instead of path.  The easiest way to migrate to this might be to add a new `hstore` field similar to the existing tags field, but using content_ids. Since these tags will always be found in the "links" field, I'd suggest calling that new field "links".

**Comment by mobaig** [comment]
I've clearly missed something here. Will rework and push some changes.

**Comment by elliotcm** [comment]
:+1: to @rboulton's comment

**Comment by mobaig** [comment]
Re-opening after I've made some changes.

**Comment by elliotcm** [comment]
Looks like this was superseded by https://github.com/alphagov/email-alert-api/pulls/82 so I'm deleting this branch.

**Pull request closed without merging**
